/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_coldwizards_demoapp_ndk_NdkJniUtils */

#ifndef _Included_com_coldwizards_demoapp_ndk_NdkJniUtils
#define _Included_com_coldwizards_demoapp_ndk_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_coldwizards_demoapp_ndk_NdkJniUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_coldwizards_demoapp_ndk_NdkJniUtils_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
